#pragma once
#include <cstdint>
// Genre badge for the info box: Apple genre id -> label + colour. The table is generated by
// tools/gen_genres.py from Apple's genre tree (subgenres take their parent's badge, with
// overrides such as Baile Funk -> FUNK BR). Spec 2026-10-08-genre-badge-design.md. PURE, tested.
namespace genrebadge {
constexpr int W = 58, H = 12;        // fits 9 letters of font 1 (6 px each) with padding
struct Badge { const char* label; uint16_t color; };
int count();                         // number of badges; the "???" fallback is the last one
const Badge& at(int index);          // 0 <= index < count()
uint8_t forGenreId(uint32_t id);     // badge index; unknown id -> the "???" fallback
int idCount();                       // generated table size (tests)
uint32_t idAt(int i);                // i-th id, ascending (tests)
}
