#pragma once
#include <cstddef>
#include <cstdint>
// Bundled national Pokédex (#1-1025): ASCII name + primary type, generated by
// tools/gen_dex.py. PURE, host-tested. Replaced a ~4.2 s PokeAPI request per
// track (see README "Design & performance history").
namespace dex {
constexpr int COUNT = 1025;
const char* name(int n);    // "" if out of range
const char* type(int n);    // lowercase PokeAPI type name ("grass"), "" if out of range
int fromRandom(uint32_t r); // 1..COUNT
// Fallback sprite (PokeAPI sprites repo) for dex n.
void spriteUrl(int n, char* out, size_t len);
}
