"""Generate src/ui/status_sprite.inc: a Pokemon sprite bundled in flash for the status screens
("No signal...", "Nothing playing"), which show exactly when nothing can be downloaded.
Run: python tools/gen_status_sprite.py [dex]   (default 25 = Pikachu; output is committed)
"""
import os
import struct
import sys
import urllib.request
import zlib

DEX = int(sys.argv[1]) if len(sys.argv) > 1 else 25
URL = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/%d.png" % DEX
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "ui", "status_sprite.inc")


def decode_png(data):
    """Minimal decoder: non-interlaced indexed (1/2/4/8-bit) or 8-bit RGBA -> rows of (r,g,b,a)."""
    assert data[:8] == b"\x89PNG\r\n\x1a\n", "not a PNG"
    pos, idat, plte, trns = 8, b"", [], b""
    while pos < len(data):
        n = struct.unpack(">I", data[pos:pos + 4])[0]
        kind, body = data[pos + 4:pos + 8], data[pos + 8:pos + 8 + n]
        if kind == b"IHDR":
            w, h, depth, ctype, _, _, interlace = struct.unpack(">IIBBBBB", body)
        elif kind == b"PLTE":
            plte = [tuple(body[i:i + 3]) for i in range(0, len(body), 3)]
        elif kind == b"tRNS":
            trns = body
        elif kind == b"IDAT":
            idat += body
        pos += 12 + n
    assert interlace == 0 and (ctype == 3 or (ctype == 6 and depth == 8)), (ctype, depth)
    bits = depth if ctype == 3 else 32
    stride = (w * bits + 7) // 8
    fbpp = max(1, bits // 8)
    raw = zlib.decompress(idat)
    rows, prev = [], bytearray(stride)
    for y in range(h):
        f = raw[y * (stride + 1)]
        line = bytearray(raw[y * (stride + 1) + 1:(y + 1) * (stride + 1)])
        for i in range(stride):
            a = line[i - fbpp] if i >= fbpp else 0
            b = prev[i]
            c = prev[i - fbpp] if i >= fbpp else 0
            if f == 1:
                line[i] = (line[i] + a) & 255
            elif f == 2:
                line[i] = (line[i] + b) & 255
            elif f == 3:
                line[i] = (line[i] + (a + b) // 2) & 255
            elif f == 4:
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                line[i] = (line[i] + (a if pa <= pb and pa <= pc else b if pb <= pc else c)) & 255
        prev = line
        px = []
        for x in range(w):
            if ctype == 6:
                px.append(tuple(line[x * 4:x * 4 + 4]))
            else:
                bit = x * depth
                idx = (line[bit // 8] >> (8 - depth - bit % 8)) & ((1 << depth) - 1)
                px.append(plte[idx] + (trns[idx] if idx < len(trns) else 255,))
        rows.append(px)
    return w, h, rows


w, h, rows = decode_png(urllib.request.urlopen(URL).read())
opaque = [(x, y) for y in range(h) for x in range(w) if rows[y][x][3] >= 128]
x0, x1 = min(x for x, _ in opaque), max(x for x, _ in opaque)
y0, y1 = min(y for _, y in opaque), max(y for _, y in opaque)
cw, ch = x1 - x0 + 1, y1 - y0 + 1

px, mask = [], bytearray((cw * ch + 7) // 8)
for y in range(ch):
    for x in range(cw):
        r, g, b, a = rows[y0 + y][x0 + x]
        i = y * cw + x
        px.append(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3))
        if a >= 128:
            mask[i >> 3] |= 0x80 >> (i & 7)

with open(OUT, "w", encoding="ascii", newline="\n") as f:
    f.write("// Generated by tools/gen_status_sprite.py from PokeAPI sprite #%d. Do not edit.\n" % DEX)
    f.write("static const int SPRITE_W = %d, SPRITE_H = %d;\n" % (cw, ch))
    f.write("static const uint16_t SPRITE_PX[%d] = {\n" % len(px))
    for i in range(0, len(px), 12):
        f.write("    " + ", ".join("0x%04X" % v for v in px[i:i + 12]) + ",\n")
    f.write("};\n")
    f.write("static const uint8_t SPRITE_MASK[%d] = {\n" % len(mask))
    for i in range(0, len(mask), 16):
        f.write("    " + ", ".join("0x%02X" % v for v in mask[i:i + 16]) + ",\n")
    f.write("};\n")
print("wrote %s (%dx%d)" % (OUT, cw, ch))
