"""Generate src/pokemon/dex_data.inc from PokeAPI CSV data (dev-time; output is committed).

Why: the deck used to call https://pokeapi.co/api/v2/pokemon/<n> on every track change
just to get a name and a type: ~4.2 s of TLS + a multi-hundred-KB JSON body on a board
without PSRAM. 1025 names + primary types fit in ~20 KB of flash instead.
Run:  python tools/gen_dex.py
"""
import csv
import io
import os
import unicodedata
import urllib.request

BASE = "https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv/"
COUNT = 1025
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "pokemon", "dex_data.inc")


def rows(name):
    data = urllib.request.urlopen(BASE + name).read().decode("utf-8")
    return list(csv.DictReader(io.StringIO(data)))


def ascii_name(s):
    s = s.replace("♀", " F").replace("♂", " M").replace("’", "'")
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode()
    return s.replace('"', "'")


types = {int(r["id"]): r["identifier"] for r in rows("types.csv")}
names = {int(r["pokemon_species_id"]): r["name"]
         for r in rows("pokemon_species_names.csv") if r["local_language_id"] == "9"}
first_type = {int(r["pokemon_id"]): int(r["type_id"])
              for r in rows("pokemon_types.csv") if r["slot"] == "1"}

type_ids = list(range(1, 19))                      # normal .. fairy
assert all(first_type[n] in type_ids for n in range(1, COUNT + 1))

with open(OUT, "w", encoding="ascii", newline="\n") as f:
    f.write("// Generated by tools/gen_dex.py from PokeAPI CSV data. Do not edit.\n")
    f.write("static const char* const TYPE_NAMES[] = {\n")
    for t in type_ids:
        f.write('    "%s",\n' % types[t])
    f.write("};\n")
    f.write("static const DexEntry DEX[%d] = {\n" % COUNT)
    for n in range(1, COUNT + 1):
        f.write('    {"%s", %d},\n' % (ascii_name(names[n]), first_type[n] - 1))
    f.write("};\n")
print("wrote", OUT)
