"""Generate src/ui/genre_data.inc from Apple's music genre tree (dev-time; output is committed).

Every Apple genre id maps to one of the deck's genre badges: a top-level genre and all its
subgenres take the TOP badge, with OVERRIDES winning (Baile Funk -> FUNK BR, K-pop -> K-POP ...).
Ids not mapped fall back to the grey "???" badge at runtime. Spec:
docs/superpowers/specs/2026-10-08-genre-badge-design.md
Run:  python tools/gen_genres.py
"""
import json
import os
import urllib.request

TREE_URL = "https://itunes.apple.com/WebObjects/MZStoreServices.woa/ws/genres?id=34&cc=br"
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "ui", "genre_data.inc")

# Badge order is the runtime index; "???" must stay last (unknown-id fallback).
BADGES = [
    ("POP", 0xF070A8), ("K-POP", 0xD040C0), ("J-POP", 0xF08890), ("RAP", 0xC89818),
    ("R&B", 0xA04880), ("FUNK", 0xE07020), ("ROCK", 0xB83030), ("METAL", 0x505058),
    ("ALT", 0x6858A8), ("ELECTRO", 0x18A8D8), ("DANCE", 0x20B898), ("BRASIL", 0x1E9E4E),
    ("FUNK BR", 0xE0B000), ("SERTANEJO", 0xA87030), ("MPB", 0x2E8C80), ("SAMBA", 0xE89818),
    ("PAGODE", 0x58A838), ("FORRO", 0xC85828), ("AXE", 0xF07800), ("LATIN", 0xE05040),
    ("REGGAE", 0x3C8C28), ("JAZZ", 0x3858A0), ("GOSPEL", 0xC0A048), ("CLASSIC", 0x8C6A48),
    ("OST", 0x687898), ("COUNTRY", 0xA08048), ("FOLK", 0x788C48), ("WORLD", 0x4890B0),
    ("???", 0x8890A0),
]
TOP = {
    14: "POP", 50000066: "POP", 50000064: "POP", 18: "RAP", 15: "R&B", 21: "ROCK", 20: "ALT",
    7: "ELECTRO", 17: "DANCE", 1122: "BRASIL", 12: "LATIN", 100024: "LATIN", 24: "REGGAE",
    11: "JAZZ", 2: "JAZZ", 22: "GOSPEL", 5: "CLASSIC", 1290: "CLASSIC", 16: "OST",
    6: "COUNTRY", 1289: "FOLK", 10: "FOLK", 50000068: "FOLK",
    19: "WORLD", 1203: "WORLD", 1197: "WORLD", 1262: "WORLD", 1232: "WORLD", 1243: "WORLD",
    1300: "WORLD", 100084: "WORLD", 1299: "WORLD", 50000121: "WORLD",
}
OVERRIDES = {
    51: "K-POP", 1252: "K-POP", 27: "J-POP", 30: "J-POP", 28: "J-POP", 29: "OST", 50000063: "OST",
    1139: "FUNK", 1153: "METAL", 1149: "METAL", 1151: "METAL", 1152: "METAL",
    1229: "FUNK BR", 1228: "SERTANEJO", 1225: "MPB", 1221: "MPB", 1227: "SAMBA", 1222: "SAMBA",
    1226: "PAGODE", 1223: "FORRO", 1220: "AXE",
}

index = {label: i for i, (label, _) in enumerate(BADGES)}
assert BADGES[-1][0] == "???"
assert all(b in index for b in list(TOP.values()) + list(OVERRIDES.values()))

req = urllib.request.Request(TREE_URL, headers={"User-Agent": "PokeDeck/1.0 (gen_genres.py)"})
tree = json.loads(urllib.request.urlopen(req, timeout=30).read())["34"]["subgenres"]

ids = {}


def walk(gid, node, parent):
    badge = OVERRIDES.get(gid, TOP.get(gid, parent))
    if badge:
        ids[gid] = index[badge]
    for sub_id, sub in node.get("subgenres", {}).items():
        walk(int(sub_id), sub, badge)


for gid, node in tree.items():
    walk(int(gid), node, None)

with open(OUT, "w", encoding="ascii", newline="\n") as f:
    f.write("// Generated by tools/gen_genres.py from Apple's genre tree. Do not edit.\n")
    f.write("static const Badge BADGES[] = {\n")
    for label, c in BADGES:
        f.write('    {"%s", rgb(0x%02X, 0x%02X, 0x%02X)},\n' % (label, c >> 16, (c >> 8) & 255, c & 255))
    f.write("};\n")
    f.write("static const IdBadge IDS[] = {   // sorted by id\n")
    for gid in sorted(ids):
        f.write("    {%d, %d},\n" % (gid, ids[gid]))
    f.write("};\n")
print("wrote", OUT, "-", len(ids), "ids")
